# Generated by Django 4.2.5 on 2023-09-16 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='To Do', max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deadline', models.DateField()),
                ('time_remaining', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('fd6a952c-f2dd-4f2b-8a7d-7e4d1b241d88'), editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
