# Generated by Django 4.2.5 on 2023-09-16 22:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e531879b-35b8-4253-ad87-ce3b99cb3099'), editable=False, primary_key=True, serialize=False),
        ),
    ]
