# Generated by Django 4.2.5 on 2023-09-16 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0002_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1373ed9d-81c4-4b97-a901-4b07e5cadb12'), editable=False, primary_key=True, serialize=False),
        ),
    ]
