# Generated by Django 4.2.5 on 2023-09-20 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0003_alter_user_model_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_model',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task_model',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task_model',
            name='time_remaining',
        ),
        migrations.RemoveField(
            model_name='task_model',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='task_model',
            name='task_id',
            field=models.UUIDField(default=uuid.UUID('7a8b659b-9597-4e85-9b1a-b5c4659cfcee'), editable=False),
        ),
        migrations.AlterField(
            model_name='task_model',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('695f048f-12de-406e-b45a-dc1048be8117'), editable=False, primary_key=True, serialize=False),
        ),
    ]
