# Generated by Django 4.2.5 on 2023-09-20 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0004_remove_task_model_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_model',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task_model',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task_model',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task_model',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='task_model',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='task_model',
            name='task',
            field=models.TextField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('82ffa3bf-626b-42eb-9b0a-1822481799f6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
