# Generated by Django 4.2.5 on 2023-09-22 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0006_task_model_task_id_alter_task_model_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task_model',
            name='task',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='task_model',
            name='task_id',
            field=models.UUIDField(default=277962967959177800890665735899634945248, editable=False),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb5fd93a-63c3-4ba6-bf18-de6bcec42f39'), editable=False, primary_key=True, serialize=False),
        ),
    ]
