# Generated by Django 4.2.5 on 2023-09-22 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0007_alter_task_model_deadline_alter_task_model_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='task_id',
            field=models.UUIDField(default=116431397569226975293142288242303550620, editable=False),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fbec07ac-16e9-4d40-bfe8-da9d00743b4b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
