# Generated by Django 4.2.5 on 2023-09-22 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0008_alter_task_model_task_id_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='task_id',
            field=models.UUIDField(default=143364289047440404242367440963766591030, editable=False),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a3dbc1d1-4b36-40e8-8006-ce52758d38ea'), editable=False, primary_key=True, serialize=False),
        ),
    ]
