# Generated by Django 4.2.5 on 2023-09-22 17:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0009_alter_task_model_task_id_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='task_id',
            field=models.UUIDField(default=244025156589506229471290169944024588432, editable=False),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f04c14c8-06a2-4ab9-99d0-c5f42d048714'), editable=False, primary_key=True, serialize=False),
        ),
    ]
