# Generated by Django 4.2.5 on 2023-09-22 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0010_alter_task_model_task_id_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='task_id',
            field=models.UUIDField(default=275477858693717072416675264782534414311, editable=False),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7db4b0cd-2045-4988-9a60-a213973f2058'), editable=False, primary_key=True, serialize=False),
        ),
    ]
