# Generated by Django 4.2.5 on 2023-09-22 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0012_alter_task_model_task_id_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='task_id',
            field=models.UUIDField(default=321284973124673304084438600024997633167, editable=False),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ff36c7d4-a5b9-4919-bdf0-d20fa1445fd3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
