# Generated by Django 4.2.5 on 2023-09-22 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0013_alter_task_model_task_id_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='task_id',
            field=models.UUIDField(default=230741420083321406640708106718770100892, editable=False),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f7df430-aa5c-4f21-a572-fba8777e25bf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
