# Generated by Django 4.2.5 on 2023-09-22 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0014_alter_task_model_task_id_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='task_id',
            field=models.UUIDField(default=11452596192435858296, editable=False),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('942cc9a2-e647-4a79-a52f-eb76b33b8601'), editable=False, primary_key=True, serialize=False),
        ),
    ]
