# Generated by Django 4.2.5 on 2023-09-22 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0015_alter_task_model_task_id_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='task_id',
            field=models.BigIntegerField(default=170768955764844881657761975932941558676, editable=False),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('453381b8-05ec-41fe-828d-de3ced32ed74'), editable=False, primary_key=True, serialize=False),
        ),
    ]
