# Generated by Django 4.2.5 on 2023-09-22 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0016_alter_task_model_task_id_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='task_id',
            field=models.BigIntegerField(default=13356871308853499566, editable=False),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('047e6a64-b6bc-4f95-b88e-b34a23727597'), editable=False, primary_key=True, serialize=False),
        ),
    ]
