# Generated by Django 4.2.5 on 2023-09-22 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0018_alter_task_model_task_id_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='task_id',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97a4c711-8e77-4b57-a6d9-2877461cbe44'), editable=False, primary_key=True, serialize=False),
        ),
    ]
