# Generated by Django 4.2.5 on 2023-09-22 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0019_alter_task_model_task_id_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bff3e4cf-d177-4cd3-97a0-409b92f6989f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
