# Generated by Django 4.2.5 on 2023-09-22 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CSC394_demo', '0021_task_model_complete_alter_user_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c4283882-2b8f-44df-958c-dee211535913'), editable=False, primary_key=True, serialize=False),
        ),
    ]
